Repository TodoCraftAcademy/keep-my-ass, pull requests merged in 2025-07, with the labels that each got.

#1 创建1223分支
  src/renderer/src/App.vue
Labels: enhancement

#18 更新会议记录
  doc/会议/第一周/头脑风暴.md
  doc/会议/第一周/架构简述.md
  doc/会议/第一周/第一周MVP.md
Labels: doc

#21 feat: 初步完成数据结构及业务逻辑实现
  docs/datamodel_design.md
  docs/store_design.md
  package.json
  pnpm-lock.yaml
  src/renderer/src/stores/taskStore.ts
  src/renderer/src/types/Todo.ts
Labels: help wanted

#26 [feat] 配置基础的GitHub Actions CI工作流
  .github/workflows/ci.yml
  tsconfig.node.json
Labels: enhancement
